import { CONFIG } from "./config.js";
import { PRODUCTS } from "./data.js";
const API_URL=CONFIG.API_URL;
const num=v=>Number(v||0);
const mobile=v=>String(v||"").replace(/[\s\-()]/g,"");
async function request(action,payload={},method="GET"){
 const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),CONFIG.API.timeout||15000);
 try{let url=`${API_URL}?action=${encodeURIComponent(action)}`;const options={method,signal:controller.signal};
  if(method==="GET")Object.entries(payload).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=="")url+=`&${encodeURIComponent(k)}=${encodeURIComponent(v)}`});
  else{options.headers={"Content-Type":"text/plain;charset=utf-8"};options.body=JSON.stringify({action,...payload})}
  const response=await fetch(url,options);if(!response.ok)throw new Error(`Backend request failed (${response.status}).`);const result=await response.json();if(!result.success)throw new Error(result.error||"Backend request failed.");return result;
 }finally{clearTimeout(timer)}}
function totalsObject(r){return{subtotal:num(r.subtotal),discount:num(r.discount),tax:num(r.tax),grandTotal:num(r.total),totalQuantity:num(r.totalQuantity)}}
function normalizeOrder(r,items=[]){if(!r)return null;return{id:r.salesOrderId,number:r.salesOrderNumber,status:r.status,customer:{id:r.customerId,mobile:r.customerMobile,phone:r.customerMobile,name:r.customerName||"Walk-in Customer",company:r.customerCompany||"",email:r.customerEmail||"",address:r.customerAddress||"",notes:r.notes||""},items:items.map(x=>({productId:x.productId,brandId:x.brandId,brandName:x.brandName,model:x.model,name:x.productName,sku:x.sku,category:x.category||"",quantity:num(x.quantity),unitPrice:num(x.unitPrice),discount:num(x.discount),tax:num(x.tax),lineTotal:num(x.total)})),total:totalsObject(r),subtotal:num(r.subtotal),discount:num(r.discount),tax:num(r.tax),totalQuantity:num(r.totalQuantity),itemCount:num(r.itemCount),notes:r.notes||"",createdBy:{id:r.salespersonId,name:r.salespersonName,role:"salesperson"},createdAt:r.createdAt,updatedAt:r.updatedAt}}
function normalizeInvoice(r,items=[]){if(!r)return null;return{id:r.invoiceId,number:r.invoiceNumber,salesOrderId:r.salesOrderId||"",salesOrderNumber:r.salesOrderNumber||"",customer:{id:r.customerId,mobile:r.customerMobile,phone:r.customerMobile,name:r.customerName||"Walk-in Customer",company:r.customerCompany||"",email:r.customerEmail||"",address:r.customerAddress||"",notes:r.notes||""},cashier:{id:r.cashierId,name:r.cashierName},paymentMethod:r.paymentMethod,status:r.status,items:items.map(x=>({productId:x.productId,brandId:x.brandId,brandName:x.brandName,model:x.model,name:x.productName,sku:x.sku,category:x.category||"",quantity:num(x.quantity),unitPrice:num(x.unitPrice),discount:num(x.discount),tax:num(x.tax),lineTotal:num(x.total)})),total:totalsObject(r),subtotal:num(r.subtotal),discount:num(r.discount),tax:num(r.tax),totalQuantity:num(r.totalQuantity),itemCount:num(r.itemCount),notes:r.notes||"",createdAt:r.createdAt}}
async function getOrder(id){const r=await request("salesOrder",{salesOrderId:id,salesOrderNumber:id});return normalizeOrder(r.salesOrder,r.items||[])}
function mapItems(items,backendProducts){return(items||[]).map(item=>{const local=PRODUCTS.find(p=>p.id===item.productId)||item;const model=String(local.model||item.model||"").toLowerCase(),sku=String(local.sku||item.sku||"").toLowerCase(),name=String(local.name||item.name||"").toLowerCase();const p=backendProducts.find(x=>String(x.model||"").toLowerCase()===model||String(x.sku||"").toLowerCase()===sku||String(x.name||"").toLowerCase()===name);if(!p)throw new Error(`Product is not configured in Google Sheets: ${local.model||local.name||item.productId}`);return{productId:p.productId,quantity:num(item.quantity),unitPrice:num(item.unitPrice??local.price),discount:num(item.discount),tax:num(item.tax)}})}
export const Backend={
 async health(){return request("health")},
 async listBrands(){const r=await request("brands");return r.brands||[]},
 async listProducts(p={}){const r=await request("products",p);return r.products||[]},
 async listCustomers(p={}){const r=await request("customers",p);return r.customers||[]},
 async listSalesOrders(p={}){const r=await request("salesOrders",p);return Promise.all((r.salesOrders||[]).map(x=>getOrder(x.salesOrderId||x.salesOrderNumber)))},
 async findSalesOrders(q=""){q=String(q||"").trim();if(!q)return this.listSalesOrders();const n=mobile(q),numeric=/^\+?\d+$/.test(n);const r=await request("salesOrders",numeric?{mobile:n}:{salesOrderNumber:q});let rows=r.salesOrders||[];if(!rows.length&&!numeric){const all=await request("salesOrders");const needle=q.toLowerCase();rows=(all.salesOrders||[]).filter(x=>[x.salesOrderNumber,x.customerName,x.customerMobile].some(v=>String(v||"").toLowerCase().includes(needle)))}return Promise.all(rows.map(x=>getOrder(x.salesOrderId||x.salesOrderNumber)))},
 async getSalesOrder(id){try{return await getOrder(id)}catch{return null}},
 async createSalesOrder(order){const products=await this.listProducts(),c=order.customer||{};const r=await request("createSalesOrder",{customerMobile:mobile(c.mobile||c.phone),customerName:c.name||"Walk-in Customer",customerCompany:c.company||"",customerEmail:c.email||"",customerAddress:c.address||"",salespersonId:order.createdBy?.id||"",salespersonName:order.createdBy?.name||"Salesperson",notes:order.notes||c.notes||"",discount:num(order.discount),tax:num(order.tax),items:mapItems(order.items,products)},"POST");return normalizeOrder(r.salesOrder,r.items||[])},
 async updateSalesOrder(id,patch){return request("updateSalesOrder",{salesOrderId:id,...patch},"POST")},
 async createInvoice(invoice){const u=invoice.createdBy||invoice.cashier||{};const r=await request("createInvoice",{salesOrderId:invoice.salesOrderId||invoice.orderId||invoice.id,paymentMethod:String(invoice.paymentMethod||"CASH").toUpperCase().replace(/\s+/g,"_"),cashierId:u.id||u.userId||"",cashierName:u.name||"Cashier",notes:invoice.notes||""},"POST");return normalizeInvoice(r.invoice,r.items||[])},
 async createDirectInvoice(invoice){const products=await this.listProducts(),c=invoice.customer||{},u=invoice.createdBy||invoice.cashier||{};const r=await request("createDirectInvoice",{customerMobile:mobile(c.mobile||c.phone),customerName:c.name||"Walk-in Customer",customerCompany:c.company||"",customerEmail:c.email||"",customerAddress:c.address||"",cashierId:u.id||u.userId||"",cashierName:u.name||"Cashier",paymentMethod:String(invoice.paymentMethod||"CASH").toUpperCase().replace(/\s+/g,"_"),notes:invoice.notes||c.notes||"",discount:num(invoice.discount),tax:num(invoice.tax),items:mapItems(invoice.items,products)},"POST");return normalizeInvoice(r.invoice,r.items||[])},
 async getInvoice(id){const r=await request("invoice",{invoiceId:id});return normalizeInvoice(r.invoice,r.items||[])},
 async dashboard(){return request("dashboard")}
};
