import {Store} from './storage.js';
import {snapshotCart,cartEntries,totals,groupByBrand,clearCart} from './cart.js';
import {Backend} from './backend.js';
import {getBrand} from './data.js';
import {formatCurrency} from './config.js';

const A=document.querySelector('#app'),E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])),M=v=>formatCurrency(Number(v||0)),S=()=>Store.get().session,C=()=>S()?.role==='cashier'||S()?.role==='admin';
let cs=[],loaded=false,cid=localStorage.getItem('th_customer')||'',draft=JSON.parse(localStorage.getItem('th_customer_draft')||'null')||{},pay=localStorage.getItem('th_payment')||'CASH',disc=0,busy=false,stamp='';
const save=()=>{localStorage.setItem('th_customer',cid);localStorage.setItem('th_customer_draft',JSON.stringify(draft));localStorage.setItem('th_payment',pay)};
const toast=(m,t='success')=>{const r=document.querySelector('#toast-root');if(!r)return;const x=document.createElement('div');x.className='toast '+t;x.textContent=m;r.appendChild(x);setTimeout(()=>x.remove(),2800)};
async function load(){if(loaded)return;try{cs=await Backend.listCustomers()}catch(e){cs=[];toast('Customer database unavailable: '+e.message,'error')}loaded=true;stamp='';scan()}
const get=()=>cid==='__new__'?draft:cs.find(c=>String(c.customerId||c.id)===cid)||{};
function customer(){const c=get();return `<div class="th-customer"><div class="eyebrow">CUSTOMER</div><h3>Customer database</h3><select id="th-customer"><option value="">Select customer before transaction...</option>${cs.map(c=>{const i=String(c.customerId||c.id);return `<option value="${E(i)}" ${i===cid?'selected':''}>${E(c.name||'Customer')}${c.mobile?' • '+E(c.mobile):''}${c.company?' • '+E(c.company):''}</option>`}).join('')}<option value="__new__" ${cid==='__new__'?'selected':''}>＋ Add new customer</option></select>${cid==='__new__'?`<div class="th-fields">${['name','mobile','company','email'].map(k=>`<label>${k==='mobile'?'Mobile number':k[0].toUpperCase()+k.slice(1)}${k==='name'||k==='mobile'?' *':''}<input data-th="${k}" value="${E(draft[k]||'')}"></label>`).join('')}<label class="th-wide">Address<textarea data-th="address">${E(draft.address||'')}</textarea></label><label class="th-wide">Notes<textarea data-th="notes">${E(draft.notes||'')}</textarea></label></div>`:cid?`<div class="th-summary"><strong>${E(c.name||'Customer')}</strong><span>${E(c.mobile||c.phone||'')}</span>${c.company?`<span>${E(c.company)}</span>`:''}</div>`:'<p class="muted">A customer is required before checkout.</p>'}</div>`}
function payment(t){return `<div class="th-payment"><div class="eyebrow">PAYMENT</div><h3>Payment</h3><label>Payment method<select id="th-pay"><option value="CASH" ${pay==='CASH'?'selected':''}>Cash</option><option value="KNET" ${pay==='KNET'?'selected':''}>KNET</option><option value="CARD" ${pay==='CARD'?'selected':''}>Card</option><option value="BANK_TRANSFER" ${pay==='BANK_TRANSFER'?'selected':''}>Bank Transfer</option></select></label><div class="summary-line"><span>Subtotal</span><strong>${M(t.subtotal)}</strong></div><label>Discount<input id="th-disc" type="number" min="0" step="0.001" value="${disc.toFixed(3)}"></label><div class="summary-line"><span>Tax</span><strong>${M(t.tax)}</strong></div><div class="grand-total"><span>Total</span><strong>${M(t.grandTotal)}</strong></div><button class="primary-button full big" id="th-complete" ${cartEntries().length?'':'disabled'}>${C()?'Create Invoice':'Create Sales Order'}</button><button class="danger-button full" id="th-clear">Clear Entire Order</button></div>`}
function enhance(el){if(!el)return;const old=el.innerHTML,t=totals(disc);el.classList.add('th-cart');el.innerHTML=customer()+`<div class="th-items"><div class="eyebrow">CART</div><h3>Current order <span>${cartEntries().reduce((n,x)=>n+x.quantity,0)} items</span></h3>${groupByBrand().map(g=>`<div><strong>${E(g.brand.name)}</strong><span>${g.items.reduce((n,x)=>n+x.quantity,0)} pcs</span></div>`).join('')||'<p class="muted">No products selected yet.</p>'}</div>`+payment(t)+`<div hidden>${old}</div>`;bind(el)}
function bind(el){el.querySelector('#th-customer')?.addEventListener('change',e=>{cid=e.target.value;if(cid==='__new__')draft={};else{const c=get();draft={name:c.name||'',mobile:c.mobile||c.phone||'',company:c.company||'',email:c.email||'',address:c.address||'',notes:c.notes||''}}save();stamp='';scan()});el.querySelectorAll('[data-th]').forEach(x=>x.addEventListener('input',e=>{draft[e.target.dataset.th]=e.target.value;save()}));el.querySelector('#th-pay')?.addEventListener('change',e=>{pay=e.target.value;save()});el.querySelector('#th-disc')?.addEventListener('change',e=>{disc=Math.max(0,Number(e.target.value||0));stamp='';scan()});el.querySelector('#th-clear')?.addEventListener('click',()=>{if(confirm('Clear the entire order?')){clearCart();disc=0;stamp='';scan()}});el.querySelector('#th-complete')?.addEventListener('click',complete)}
function scan(){const l=document.querySelector('.catalog-layout')||document.querySelector('.order-layout');if(!l)return stamp='';const old=l.querySelector('.order-mini,.checkout-card');if(!old||stamp===l.className)return;stamp=l.className;const products=l.querySelector('.product-list,.order-groups');old.remove();const p=document.createElement('aside');p.className=old.className;p.innerHTML='<div></div>';l.insertBefore(p,products);enhance(p.firstElementChild||p)}
async function complete(){if(busy)return;if(!cartEntries().length)return toast('Add products before completing the transaction','error');if(!cid)return toast('Please choose a customer before continuing','error');const c=get(),customer={id:cid,name:String(c.name||'').trim(),phone:String(c.mobile||c.phone||'').trim(),company:String(c.company||'').trim(),email:String(c.email||'').trim(),address:String(c.address||'').trim(),notes:String(c.notes||'').trim()};if(!customer.name||!customer.phone)return toast('Customer name and mobile are required','error');busy=true;try{const items=snapshotCart();if(C()){const i=await Backend.createDirectInvoice({customer,items,discount:disc,tax:0,paymentMethod:pay,notes:customer.notes,createdBy:S()});A.innerHTML=`<main class="page"><div class="success-page"><div class="success-icon">✓</div><div class="eyebrow">INVOICE CREATED</div><h1>${E(i.number)}</h1><p>${E(customer.name)} • ${M(i.total.grandTotal)}</p><button class="primary-button" onclick="location.reload()">New Transaction</button></div></main>`}else{const o=await Backend.createSalesOrder({customer,items,discount:disc,tax:0,notes:customer.notes,createdBy:S()});A.innerHTML=`<main class="page"><div class="success-page"><div class="success-icon">✓</div><div class="eyebrow">SALES ORDER CREATED</div><h1>${E(o.number)}</h1><p>${E(customer.name)} • ${M(o.total.grandTotal)}</p><button class="primary-button" onclick="location.reload()">Start New Customer</button></div></main>`}clearCart();disc=0;cid='';draft={};save()}catch(e){toast(e.message||'Unable to complete transaction','error')}finally{busy=false}}
const style=document.createElement('style');style.textContent=`.catalog-layout,.order-layout{grid-template-columns:360px minmax(0,1fr)!important}.th-cart{background:#fff;border:1px solid #E1EAF7;border-radius:22px;padding:18px;box-shadow:0 10px 28px rgba(40,74,135,.06);position:sticky;top:100px;max-height:calc(100vh - 120px);overflow:auto}.th-customer{padding-bottom:16px;border-bottom:1px solid #E8EEF7}.th-customer h3,.th-items h3,.th-payment h3{margin:5px 0 10px}.th-customer select,.th-payment select,.th-payment input,.th-fields input,.th-fields textarea{width:100%;margin-top:7px;border:1px solid #DCE6F5;background:#FAFCFF;border-radius:10px;padding:10px;outline:0;color:#10234D}.th-summary{margin-top:10px;padding:10px;border-radius:10px;background:#F3F8FF}.th-summary strong,.th-summary span{display:block}.th-summary span{font-size:10px;color:#7383A3;margin-top:3px}.th-items{padding:16px 0;border-bottom:1px solid #E8EEF7}.th-items h3 span{float:right;font-size:10px;color:#7B8AA5;font-weight:600}.th-items>div:not(.eyebrow){display:flex;justify-content:space-between;padding:9px 0;border-top:1px solid #F0F3F8;font-size:11px}.th-payment{padding-top:16px}.th-payment label{display:block;font-size:10px;font-weight:800;color:#5F7092;margin:10px 0}.th-payment .grand-total{margin:12px -18px 12px;padding:16px 18px}.th-payment .danger-button{margin-top:8px}.th-fields{display:grid;grid-template-columns:1fr 1fr;gap:8px}.th-fields label{font-size:10px;font-weight:700;color:#5F7092}.th-fields .th-wide{grid-column:span 2}.th-fields textarea{resize:vertical}.th-cart button:disabled{opacity:.45;cursor:not-allowed}@media(max-width:1100px){.catalog-layout,.order-layout{grid-template-columns:1fr!important}.th-cart{position:static;max-height:none;order:-1}}@media(max-width:600px){.th-fields{grid-template-columns:1fr}.th-fields .th-wide{grid-column:span 1}}`;document.head.appendChild(style);
new MutationObserver(()=>requestAnimationFrame(scan)).observe(A,{childList:true,subtree:true});document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(a==='sales-order'||a==='direct-invoice'){e.preventDefault();e.stopImmediatePropagation();complete()}},{capture:true});load();
