const APP_NAME='TimeHouse Watch Wholesale POS';
const CONFIG={spreadsheetProperty:'POS_SPREADSHEET_ID',currency:'KWD',sheets:{brands:'Brands',products:'Products',customers:'Customers',users:'Users',salesOrders:'SalesOrders',salesOrderItems:'SalesOrderItems',invoices:'Invoices',invoiceItems:'InvoiceItems',settings:'Settings'}};
const SCHEMAS={Brands:['brandId','name','code','description','active','createdAt'],Products:['productId','brandId','brandName','sku','model','name','description','category','unitPrice','stock','active','image','createdAt'],Customers:['customerId','mobile','name','company','email','address','notes','createdAt'],Users:['userId','name','username','role','active','createdAt'],SalesOrders:['salesOrderId','salesOrderNumber','customerId','customerMobile','customerName','salespersonId','salespersonName','status','itemCount','totalQuantity','subtotal','discount','tax','total','notes','createdAt','updatedAt'],SalesOrderItems:['salesOrderItemId','salesOrderId','salesOrderNumber','productId','brandId','brandName','sku','model','productName','quantity','unitPrice','discount','tax','total','createdAt'],Invoices:['invoiceId','invoiceNumber','salesOrderId','salesOrderNumber','customerId','customerMobile','customerName','cashierId','cashierName','paymentMethod','status','itemCount','totalQuantity','subtotal','discount','tax','total','notes','createdAt'],InvoiceItems:['invoiceItemId','invoiceId','invoiceNumber','salesOrderId','productId','brandId','brandName','sku','model','productName','quantity','unitPrice','discount','tax','total','createdAt'],Settings:['key','value','description']};

function doGet(e){try{const p=e&&e.parameter?e.parameter:{};return jsonResponse_(routeRequest_('GET',p.action||'health',p,null));}catch(err){return jsonResponse_({success:false,error:err.message,stack:err.stack});}}
function doPost(e){try{const p=e&&e.parameter?e.parameter:{};let body={};if(e&&e.postData&&e.postData.contents){try{body=JSON.parse(e.postData.contents);}catch(_){}}return jsonResponse_(routeRequest_('POST',body.action||p.action||'',body,p));}catch(err){return jsonResponse_({success:false,error:err.message,stack:err.stack});}}
function routeRequest_(method,action,data,params){action=String(action||'').trim();switch(action){case'health':return apiHealth_();case'setup':return setupDatabase_();case'resetDemo':return resetDemoData_();case'brands':return getBrands_();case'products':return getProducts_(data);case'product':return getProduct_(data);case'customers':return searchCustomers_(data);case'customer':return getCustomer_(data);case'users':return getUsers_(data);case'salesOrders':return getSalesOrders_(data);case'salesOrder':return getSalesOrder_(data);case'createSalesOrder':return createSalesOrder_(data);case'updateSalesOrder':return updateSalesOrder_(data);case'invoices':return getInvoices_(data);case'invoice':return getInvoice_(data);case'createInvoice':return createInvoice_(data);case'createDirectInvoice':return createDirectInvoice_(data);case'dashboard':return getDashboard_();default:return{success:false,error:'Unknown action: '+action};}}

function setupDatabase_(){const props=PropertiesService.getScriptProperties();let id=props.getProperty(CONFIG.spreadsheetProperty),ss=null;if(id){try{ss=SpreadsheetApp.openById(id);}catch(_){}}if(!ss){ss=SpreadsheetApp.create(APP_NAME+' - Demo Database');id=ss.getId();props.setProperty(CONFIG.spreadsheetProperty,id);}Object.keys(SCHEMAS).forEach(n=>{let s=ss.getSheetByName(n);if(!s)s=ss.insertSheet(n);initializeSheet_(s,SCHEMAS[n]);});const s1=ss.getSheetByName('Sheet1');if(s1&&ss.getSheets().length>1&&s1.getLastRow()===0)ss.deleteSheet(s1);seedDemoData_(ss);return{success:true,message:'Database is ready.',spreadsheetId:ss.getId(),spreadsheetUrl:ss.getUrl(),sheets:Object.keys(SCHEMAS)};}
function initializeSheet_(sheet,headers){if(sheet.getLastRow()===0){sheet.getRange(1,1,1,headers.length).setValues([headers]);formatHeader_(sheet,headers.length);return;}const existing=sheet.getRange(1,1,1,Math.max(sheet.getLastColumn(),headers.length)).getValues()[0];if(headers.some((h,i)=>existing[i]!==h)){sheet.getRange(1,1,1,headers.length).setValues([headers]);formatHeader_(sheet,headers.length);}}
function formatHeader_(sheet,n){sheet.getRange(1,1,1,n).setFontWeight('bold');sheet.setFrozenRows(1);for(let i=1;i<=n;i++)sheet.autoResizeColumn(i);}
function seedDemoData_(ss){seedBrands_(ss);seedProducts_(ss);seedCustomers_(ss);seedUsers_(ss);seedSettings_(ss);}

function seedBrands_(ss){const s=ss.getSheetByName('Brands');if(s.getLastRow()>1)return;const now=new Date();appendRows_(s,[['BR-001','CASIO','CAS','Digital • Classic • Everyday',true,now],['BR-002','CITIZEN','CIT','Precision • Eco-Drive • Dress',true,now],['BR-003','SEIKO','SEI','Japanese • Automatic • Heritage',true,now],['BR-004','ORIENT','ORI','Automatic • Japanese Craft',true,now],['BR-005','TIMEX','TIM','American • Casual • Heritage',true,now],['BR-006','Q&Q','QQ','Affordable • Everyday • Reliable',true,now],['BR-007','ALBA','ALB','Japanese • Contemporary • Value',true,now],['BR-008','EDIFICE','EDI','Motorsport • Chronograph • Sport',true,now],['BR-009','G-SHOCK','GSH','Tough • Sport • Iconic',true,now],['BR-010','TITAN','TIT','Indian • Modern • Elegant',true,now],['BR-011','FOSSIL','FOS','Fashion • Leather • Lifestyle',true,now],['BR-012','NAVIFORCE','NAV','Bold • Sport • Value',true,now]]);}

function seedProducts_(ss){const s=ss.getSheetByName('Products');const now=new Date();const rows=[
['PRD-001','BR-001','CASIO','CAS-AE1200','AE-1200WH','Digital World Time','Digital World Time','Digital',8.5,120,true,'',now],
['PRD-002','BR-001','CASIO','CAS-F91W','F-91W','Classic Digital','Classic Digital','Digital',4.5,200,true,'',now],
['PRD-003','BR-001','CASIO','CAS-A158','A158WA','Vintage Digital','Vintage Digital','Digital',5.5,85,true,'',now],
['PRD-004','BR-001','CASIO','CAS-W800','W-800H','Sport Digital','Sport Digital','Sports',7.5,62,true,'',now],
['PRD-005','BR-001','CASIO','CAS-MTP1302','MTP-1302D','Classic Analog','Classic Analog','Analog',9.75,44,true,'',now],
['PRD-006','BR-001','CASIO','CAS-MDV106','MDV-106','Diver Style','Diver Style','Diver',18.5,24,true,'',now],
['PRD-007','BR-002','CITIZEN','CIT-BI5000','BI5000','Classic Quartz','Classic Quartz','Analog',12,55,true,'',now],
['PRD-008','BR-002','CITIZEN','CIT-BF500','BF500','Dress Quartz','Dress Quartz','Dress',14,38,true,'',now],
['PRD-009','BR-002','CITIZEN','CIT-EW3260','EW3260','Eco-Drive Classic','Eco-Drive Classic','Analog',28.5,20,true,'',now],
['PRD-010','BR-002','CITIZEN','CIT-NY0040','NY0040','Automatic Diver','Automatic Diver','Automatic',42,12,true,'',now],
['PRD-011','BR-003','SEIKO','SEI-SNK809','SNK809','Automatic Field','Automatic Field','Automatic',35,16,true,'',now],
['PRD-012','BR-003','SEIKO','SEI-SUR309','SUR309','Classic Quartz','Classic Quartz','Analog',27.5,18,true,'',now],
['PRD-013','BR-003','SEIKO','SEI-SRPD55','SRPD55','5 Sports Automatic','5 Sports Automatic','Sports',48,9,true,'',now],
['PRD-014','BR-003','SEIKO','SEI-SRPE55','SRPE55','Dress Automatic','Dress Automatic','Automatic',52,8,true,'',now],
['PRD-015','BR-004','ORIENT','ORI-RAAA000','RA-AA000','Diver Automatic','Diver Automatic','Automatic',22,17,true,'',now],
['PRD-016','BR-004','ORIENT','ORI-FAC000','FAC00009','Classic Bambino','Classic Bambino','Dress',31,11,true,'',now],
['PRD-017','BR-004','ORIENT','ORI-KAMASU','RA-AA0003','Kamasu Automatic','Kamasu Automatic','Diver',38.5,7,true,'',now],
['PRD-018','BR-005','TIMEX','TIM-WEEK','TW2R42500','Weekender','Weekender','Casual',15,35,true,'',now],
['PRD-019','BR-005','TIMEX','TIM-EXP','TW4B13900','Expedition','Expedition','Sports',18,24,true,'',now],
['PRD-020','BR-005','TIMEX','TIM-EASY','TW2V30100','Easy Reader','Easy Reader','Dress',19.5,19,true,'',now],
['PRD-021','BR-006','Q&Q','QQ-VR52','VR52J001Y','Classic Analog','Classic Analog','Analog',5.5,90,true,'',now],
['PRD-022','BR-006','Q&Q','QQ-M173','M173J001Y','Everyday Analog','Everyday Analog','Analog',6.25,72,true,'',now],
['PRD-023','BR-006','Q&Q','QQ-M199','M199J002Y','Digital Sport','Digital Sport','Digital',7,58,true,'',now],
['PRD-024','BR-007','ALBA','ALB-VJ42','VJ42-X179','Classic Quartz','Classic Quartz','Analog',13.5,30,true,'',now],
['PRD-025','BR-007','ALBA','ALB-AL4247','AL4247X1','Automatic','Automatic','Automatic',26,14,true,'',now],
['PRD-026','BR-007','ALBA','ALB-AH7','AH7J17X1','Active Chronograph','Active Chronograph','Chronograph',24,12,true,'',now],
['PRD-027','BR-008','EDIFICE','EDI-EFV100','EFV-100D','Classic Chronograph','Classic Chronograph','Chronograph',18.5,25,true,'',now],
['PRD-028','BR-008','EDIFICE','EDI-EFR571','EFR-571','Sport Chronograph','Sport Chronograph','Chronograph',29.5,16,true,'',now],
['PRD-029','BR-008','EDIFICE','EDI-ECB40','ECB-40','Connected Sport','Connected Sport','Sports',45,8,true,'',now],
['PRD-030','BR-009','G-SHOCK','GSH-DW5600','DW-5600','Classic Tough','Classic Tough','Sports',32,20,true,'',now],
['PRD-031','BR-009','G-SHOCK','GSH-GA2100','GA-2100','CasiOak','CasiOak','Sports',38,14,true,'',now],
['PRD-032','BR-009','G-SHOCK','GSH-GBA900','GBA-900','Sport Bluetooth','Sport Bluetooth','Sports',44,8,true,'',now],
['PRD-033','BR-010','TITAN','TIT-1805','1805SL02','Classic Analog','Classic Analog','Dress',21,18,true,'',now],
['PRD-034','BR-010','TITAN','TIT-1802','1802YM01','Workwear Classic','Workwear Classic','Dress',23.5,14,true,'',now],
['PRD-035','BR-010','TITAN','TIT-1696','1696NM01','Edge Ultra Slim','Edge Ultra Slim','Dress',35,8,true,'',now],
['PRD-036','BR-011','FOSSIL','FOS-FS5151','FS5151','Grant Chronograph','Grant Chronograph','Chronograph',29,16,true,'',now],
['PRD-037','BR-011','FOSSIL','FOS-FS4656','FS4656','Machine','Machine','Sports',31.5,13,true,'',now],
['PRD-038','BR-011','FOSSIL','FOS-ES5167','ES5167','Caroline','Caroline','Dress',34,9,true,'',now],
['PRD-039','BR-012','NAVIFORCE','NAV-9233','NF9233','Sport Chronograph','Sport Chronograph','Chronograph',8.5,42,true,'',now],
['PRD-040','BR-012','NAVIFORCE','NAV-9163','NF9163','Classic Sport','Classic Sport','Sports',7.5,55,true,'',now],
['PRD-041','BR-012','NAVIFORCE','NAV-8028','NF8028','Everyday Analog','Everyday Analog','Analog',6.75,61,true,'',now]
];
// Seed only when empty. If the sheet already contains data, preserve it.
if(s.getLastRow()<=1)appendRows_(s,rows);
}

function seedCustomers_(ss){const s=ss.getSheetByName('Customers');if(s.getLastRow()>1)return;const now=new Date();appendRows_(s,[['CUS-001','55512345','Ahmed Al-Khalid','ABC Watch Trading','ahmed@example.com','Kuwait City','Demo wholesale customer',now],['CUS-002','55567890','Mohammed Hassan','Hassan Watches','mohammed@example.com','Hawally','Demo wholesale customer',now],['CUS-003','55511122','Khaled Ali','Al Ali Trading','khaled@example.com','Farwaniya','',now],['CUS-004','55533344','Sarah Ahmed','Time Gallery','sarah@example.com','Salmiya','',now]]);}
function seedUsers_(ss){const s=ss.getSheetByName('Users');if(s.getLastRow()>1)return;const now=new Date();appendRows_(s,[['USR-001','Ahmed','ahmed','salesperson',true,now],['USR-002','Mohammed','mohammed','salesperson',true,now],['USR-003','Sara','sara','salesperson',true,now],['USR-004','Fatima','fatima','cashier',true,now],['USR-005','Khalid','khalid','cashier',true,now],['USR-006','Administrator','admin','admin',true,now]]);}
function seedSettings_(ss){const s=ss.getSheetByName('Settings');if(s.getLastRow()>1)return;appendRows_(s,[['companyName','TimeHouse Watches','Demo company name'],['companyAddress','Kuwait City, Kuwait','Company address'],['companyPhone','+965 2222 2222','Company phone'],['companyEmail','info@timehouse-demo.com','Company email'],['currency','KWD','Default currency'],['taxRate','0','Demo tax rate'],['invoicePrefix','INV','Invoice number prefix'],['salesOrderPrefix','SO','Sales order number prefix']]);}

function apiHealth_(){const ss=getDatabase_();return{success:true,app:APP_NAME,status:'connected',database:'Google Sheets',spreadsheetId:ss.getId(),spreadsheetUrl:ss.getUrl(),timestamp:new Date().toISOString()};}
function getBrands_(){return{success:true,brands:readSheetObjects_('Brands').filter(x=>String(x.active).toLowerCase()==='true'||x.active===true)};}
function getProducts_(p){p=p||{};let a=readSheetObjects_('Products').filter(x=>String(x.active).toLowerCase()==='true'||x.active===true);if(p.brandId)a=a.filter(x=>String(x.brandId).toLowerCase()===String(p.brandId).toLowerCase());if(p.brand)a=a.filter(x=>String(x.brandName).toLowerCase()===String(p.brand).toLowerCase());if(p.search){const q=String(p.search).toLowerCase();a=a.filter(x=>[x.name,x.model,x.sku,x.brandName].some(v=>String(v).toLowerCase().indexOf(q)>=0));}return{success:true,products:a};}
function getProduct_(p){p=p||{};const x=readSheetObjects_('Products').find(r=>String(r.productId)===String(p.productId)||String(r.sku).toLowerCase()===String(p.sku||'').toLowerCase());return x?{success:true,product:x}:{success:false,error:'Product not found.'};}
function searchCustomers_(p){p=p||{};let a=readSheetObjects_('Customers');if(p.mobile){const m=normalizeMobile_(p.mobile);a=a.filter(x=>normalizeMobile_(x.mobile)===m);}if(p.search){const q=String(p.search).toLowerCase();a=a.filter(x=>[x.name,x.company,x.mobile].some(v=>String(v).toLowerCase().indexOf(q)>=0));}return{success:true,customers:a};}
function getCustomer_(p){p=p||{};const m=normalizeMobile_(p.mobile||'');const x=readSheetObjects_('Customers').find(r=>String(r.customerId)===String(p.customerId||'')||normalizeMobile_(r.mobile)===m);return x?{success:true,customer:x}:{success:false,error:'Customer not found.'};}
function getUsers_(p){let a=readSheetObjects_('Users');if(p&&p.role)a=a.filter(x=>String(x.role).toLowerCase()===String(p.role).toLowerCase());return{success:true,users:a};}
function getSalesOrders_(p){p=p||{};let a=readSheetObjects_('SalesOrders');if(p.mobile){const m=normalizeMobile_(p.mobile);a=a.filter(x=>normalizeMobile_(x.customerMobile)===m);}if(p.status)a=a.filter(x=>String(x.status).toLowerCase()===String(p.status).toLowerCase());if(p.salespersonId)a=a.filter(x=>String(x.salespersonId)===String(p.salespersonId));if(p.salesOrderNumber)a=a.filter(x=>String(x.salesOrderNumber).toLowerCase()===String(p.salesOrderNumber).toLowerCase());a.sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt));return{success:true,salesOrders:a};}
function getSalesOrder_(p){p=p||{};const a=readSheetObjects_('SalesOrders');let o=p.salesOrderId?a.find(x=>String(x.salesOrderId)===String(p.salesOrderId)):null;if(!o&&p.salesOrderNumber)o=a.find(x=>String(x.salesOrderNumber).toLowerCase()===String(p.salesOrderNumber).toLowerCase());if(!o)return{success:false,error:'Sales Order not found.'};const items=readSheetObjects_('SalesOrderItems').filter(x=>String(x.salesOrderId)===String(o.salesOrderId));return{success:true,salesOrder:o,items:items};}

function createSalesOrder_(d){d=d||{};if(!Array.isArray(d.items)||!d.items.length)throw new Error('Sales Order cannot be empty.');const mobile=normalizeMobile_(d.customerMobile||(d.customer&&d.customer.mobile)||(d.customer&&d.customer.phone));if(!mobile)throw new Error('Customer mobile number is required.');let customer=findCustomerByMobile_(mobile);if(!customer)customer=createCustomer_({mobile:mobile,name:d.customerName||(d.customer&&d.customer.name)||'Walk-in Customer',company:d.customerCompany||'',email:d.customerEmail||'',address:d.customerAddress||'',notes:d.notes||''});return createOrderRecord_(d,customer,false);}
function createOrderRecord_(d,customer,isDirect){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const products=readSheetObjects_('Products'),orderId=Utilities.getUuid(),number=generateNumber_('salesOrder'),items=[];let subtotal=0,totalQty=0;(d.items||[]).forEach(input=>{const p=products.find(x=>String(x.productId)===String(input.productId));if(!p)throw new Error('Product not found: '+input.productId);const qty=Math.max(1,Number(input.quantity||0)),price=Number(input.unitPrice!==undefined?input.unitPrice:p.unitPrice),disc=Number(input.discount||0),tax=Number(input.tax||0),total=qty*price-disc+tax;items.push([Utilities.getUuid(),orderId,number,p.productId,p.brandId,p.brandName,p.sku,p.model,p.name,qty,price,disc,tax,total,new Date()]);subtotal+=qty*price;totalQty+=qty;});const discount=Number(d.discount||0),tax=Number(d.tax||0),total=subtotal-discount+tax;const order=[orderId,number,customer.customerId,normalizeMobile_(customer.mobile),customer.name,d.salespersonId||'',d.salespersonName||'Salesperson','READY',items.length,totalQty,subtotal,discount,tax,total,d.notes||'',new Date(),new Date()];appendRows_(getSheet_('SalesOrders'),[order]);appendRows_(getSheet_('SalesOrderItems'),items);return{success:true,message:'Sales Order created successfully.',salesOrder:orderToObject_(order),salesOrderId:orderId,salesOrderNumber:number,items:items.map(x=>rowToObject_('SalesOrderItems',x))};}finally{lock.releaseLock();}}
function updateSalesOrder_(d){const s=getSheet_('SalesOrders'),v=s.getDataRange().getValues(),h=v[0],id=h.indexOf('salesOrderId'),st=h.indexOf('status'),up=h.indexOf('updatedAt');for(let i=1;i<v.length;i++)if(String(v[i][id])===String(d.salesOrderId)){if(d.status!==undefined)s.getRange(i+1,st+1).setValue(d.status);s.getRange(i+1,up+1).setValue(new Date());return{success:true,message:'Sales Order updated.'};}throw new Error('Sales Order not found.');}

function getInvoices_(p){p=p||{};let a=readSheetObjects_('Invoices');if(p.mobile){const m=normalizeMobile_(p.mobile);a=a.filter(x=>normalizeMobile_(x.customerMobile)===m);}if(p.invoiceNumber)a=a.filter(x=>String(x.invoiceNumber).toLowerCase()===String(p.invoiceNumber).toLowerCase());a.sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt));return{success:true,invoices:a};}
function getInvoice_(p){p=p||{};const a=readSheetObjects_('Invoices');let i=p.invoiceId?a.find(x=>String(x.invoiceId)===String(p.invoiceId)):null;if(!i&&p.invoiceNumber)i=a.find(x=>String(x.invoiceNumber).toLowerCase()===String(p.invoiceNumber).toLowerCase());if(!i)throw new Error('Invoice not found.');return{success:true,invoice:i,items:readSheetObjects_('InvoiceItems').filter(x=>String(x.invoiceId)===String(i.invoiceId))};}
function createInvoice_(d){d=d||{};if(!d.salesOrderId)throw new Error('salesOrderId is required.');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const r=getSalesOrder_({salesOrderId:d.salesOrderId});if(!r.success)throw new Error('Sales Order not found.');const o=r.salesOrder;if(String(o.status).toUpperCase()==='INVOICED'){const old=findInvoiceBySalesOrderId_(d.salesOrderId);if(old)return{success:true,alreadyInvoiced:true,message:'Sales Order already has an invoice.',invoice:old,invoiceNumber:old.invoiceNumber};}return writeInvoice_(d,o,r.items||[],true);}finally{lock.releaseLock();}}
function createDirectInvoice_(d){d=d||{};if(!Array.isArray(d.items)||!d.items.length)throw new Error('Invoice cannot be empty.');const mobile=normalizeMobile_(d.customerMobile||(d.customer&&d.customer.mobile)||(d.customer&&d.customer.phone));if(!mobile)throw new Error('Customer mobile number is required.');let customer=findCustomerByMobile_(mobile);if(!customer)customer=createCustomer_({mobile:mobile,name:d.customerName||(d.customer&&d.customer.name)||'Walk-in Customer',company:d.customerCompany||'',email:d.customerEmail||'',address:d.customerAddress||'',notes:d.notes||''});const products=readSheetObjects_('Products'),items=[],orderId='',subtotal=0;let sub=0,qty=0;(d.items||[]).forEach(input=>{const p=products.find(x=>String(x.productId)===String(input.productId));if(!p)throw new Error('Product not found: '+input.productId);const q=Math.max(1,Number(input.quantity||0)),price=Number(input.unitPrice!==undefined?input.unitPrice:p.unitPrice),disc=Number(input.discount||0),tax=Number(input.tax||0),total=q*price-disc+tax;items.push({productId:p.productId,brandId:p.brandId,brandName:p.brandName,sku:p.sku,model:p.model,productName:p.name,quantity:q,unitPrice:price,discount:disc,tax:tax,total:total});sub+=q*price;qty+=q;});const discount=Number(d.discount||0),tax=Number(d.tax||0),total=sub-discount+tax;const invoiceId=Utilities.getUuid(),invoiceNumber=generateNumber_('invoice'),inv=[invoiceId,invoiceNumber,'','',customer.customerId,customer.mobile,customer.name,d.cashierId||'',d.cashierName||'Cashier',d.paymentMethod||'CASH','PAID',items.length,qty,sub,discount,tax,total,d.notes||'',new Date()];const lock=LockService.getScriptLock();lock.waitLock(30000);try{appendRows_(getSheet_('Invoices'),[inv]);const rows=items.map(x=>[Utilities.getUuid(),invoiceId,invoiceNumber,'',x.productId,x.brandId,x.brandName,x.sku,x.model,x.productName,x.quantity,x.unitPrice,x.discount,x.tax,x.total,new Date()]);appendRows_(getSheet_('InvoiceItems'),rows);reduceStock_(items);return{success:true,message:'Invoice created successfully.',invoiceId:invoiceId,invoiceNumber:invoiceNumber,invoice:invoiceToObject_(inv),items:rows.map(x=>rowToObject_('InvoiceItems',x))};}finally{lock.releaseLock();}}
function writeInvoice_(d,o,orderItems,fromOrder){const invoiceId=Utilities.getUuid(),invoiceNumber=generateNumber_('invoice'),inv=[invoiceId,invoiceNumber,o.salesOrderId,o.salesOrderNumber,o.customerId,o.customerMobile,o.customerName,d.cashierId||'',d.cashierName||'Cashier',d.paymentMethod||'CASH','PAID',o.itemCount,o.totalQuantity,o.subtotal,o.discount,o.tax,o.total,d.notes||'',new Date()];appendRows_(getSheet_('Invoices'),[inv]);const rows=orderItems.map(x=>[Utilities.getUuid(),invoiceId,invoiceNumber,o.salesOrderId,x.productId,x.brandId,x.brandName,x.sku,x.model,x.productName,x.quantity,x.unitPrice,x.discount,x.tax,x.total,new Date()]);appendRows_(getSheet_('InvoiceItems'),rows);reduceStock_(orderItems);if(fromOrder)updateSalesOrder_({salesOrderId:o.salesOrderId,status:'INVOICED'});return{success:true,message:'Invoice created successfully.',invoiceId:invoiceId,invoiceNumber:invoiceNumber,salesOrderNumber:o.salesOrderNumber||'',paymentMethod:d.paymentMethod||'CASH',invoice:invoiceToObject_(inv),items:rows.map(x=>rowToObject_('InvoiceItems',x))};}
function reduceStock_(items){const s=getSheet_('Products'),v=s.getDataRange().getValues(),h=v[0],pi=h.indexOf('productId'),si=h.indexOf('stock');(items||[]).forEach(item=>{for(let i=1;i<v.length;i++)if(String(v[i][pi])===String(item.productId)){s.getRange(i+1,si+1).setValue(Math.max(0,Number(v[i][si]||0)-Number(item.quantity)));break;}});}

function getDashboard_(){const orders=readSheetObjects_('SalesOrders'),invoices=readSheetObjects_('Invoices'),products=readSheetObjects_('Products'),customers=readSheetObjects_('Customers');let salesTotal=0;invoices.forEach(i=>salesTotal+=Number(i.total||0));return{success:true,stats:{products:products.length,customers:customers.length,salesOrders:orders.length,readySalesOrders:orders.filter(o=>String(o.status).toUpperCase()==='READY').length,invoicedSalesOrders:orders.filter(o=>String(o.status).toUpperCase()==='INVOICED').length,invoices:invoices.length,salesTotal:salesTotal},recentSalesOrders:orders.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,20)};}
function createCustomer_(d){const row=['CUS-'+Utilities.getUuid().substring(0,8).toUpperCase(),normalizeMobile_(d.mobile),d.name||'Walk-in Customer',d.company||'',d.email||'',d.address||'',d.notes||'',new Date()];appendRows_(getSheet_('Customers'),[row]);return customerToObject_(row);}
function findCustomerByMobile_(m){const n=normalizeMobile_(m);return readSheetObjects_('Customers').find(c=>normalizeMobile_(c.mobile)===n)||null;}
function findInvoiceBySalesOrderId_(id){return readSheetObjects_('Invoices').find(i=>String(i.salesOrderId)===String(id))||null;}
function generateNumber_(type){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const p=PropertiesService.getScriptProperties();const key=type==='invoice'?'LAST_INVOICE_NUMBER':'LAST_SALES_ORDER_NUMBER';const prefix=getSetting_(type==='invoice'?'invoicePrefix':'salesOrderPrefix')||(type==='invoice'?'INV':'SO');let n=Number(p.getProperty(key)||'0')+1;p.setProperty(key,String(n));return prefix+'-'+new Date().getFullYear()+'-'+String(n).padStart(6,'0');}finally{lock.releaseLock();}}
function getSetting_(key){const x=readSheetObjects_('Settings').find(r=>String(r.key)===String(key));return x?x.value:null;}
function resetDemoData_(){const ss=getDatabase_();['Products','Customers','Users','SalesOrders','SalesOrderItems','Invoices','InvoiceItems'].forEach(n=>{const s=ss.getSheetByName(n);if(s&&s.getLastRow()>1)s.getRange(2,1,s.getLastRow()-1,s.getLastColumn()).clearContent();});PropertiesService.getScriptProperties().deleteProperty('LAST_INVOICE_NUMBER');PropertiesService.getScriptProperties().deleteProperty('LAST_SALES_ORDER_NUMBER');seedDemoData_(ss);return{success:true,message:'Demo data has been reset.',spreadsheetId:ss.getId(),spreadsheetUrl:ss.getUrl()};}
function getDatabase_(){const p=PropertiesService.getScriptProperties();let id=p.getProperty(CONFIG.spreadsheetProperty);if(!id){id=setupDatabase_().spreadsheetId;}try{return SpreadsheetApp.openById(id);}catch(_){p.deleteProperty(CONFIG.spreadsheetProperty);return SpreadsheetApp.openById(setupDatabase_().spreadsheetId);}}
function getSheet_(n){const s=getDatabase_().getSheetByName(n);if(!s)throw new Error('Sheet not found: '+n);return s;}
function readSheetObjects_(n){const s=getSheet_(n),v=s.getDataRange().getValues();if(v.length<=1)return[];const h=v[0];return v.slice(1).filter(r=>r.some(x=>x!==''&&x!==null)).map(r=>{const o={};h.forEach((k,i)=>o[k]=normalizeValue_(r[i]));return o;});}
function appendRows_(s,rows){if(!rows||!rows.length)return;s.getRange(s.getLastRow()+1,1,rows.length,rows[0].length).setValues(rows);}
function normalizeValue_(v){return Object.prototype.toString.call(v)==='[object Date]'?v.toISOString():v;}
function normalizeMobile_(v){return String(v||'').replace(/[\s\-()]/g,'');}
function rowToObject_(n,row){const o={};SCHEMAS[n].forEach((h,i)=>o[h]=normalizeValue_(row[i]));return o;}
function orderToObject_(r){return rowToObject_('SalesOrders',r);}
function invoiceToObject_(r){return rowToObject_('Invoices',r);}
function customerToObject_(r){return rowToObject_('Customers',r);}
function jsonResponse_(d){return ContentService.createTextOutput(JSON.stringify(d)).setMimeType(ContentService.MimeType.JSON);}
